//! GENERATED by `python -m aletheia_ml install` from the `aletheia-ml` feature contract.
//! Do not edit by hand: the hash below is what makes a blob whose feature *meanings* have moved a
//! named refusal at load time instead of a silently rotated set of columns.
//!
//! Corpus: borg2019. Feature contract: a9e2674a721ded3db87b8aa2da0c09f02dcebd56ea1c6f4df50b62e35a457403

/// Number of features the kernel must supply to [`crate::mlrisk::RiskAdvisor::advise`].
pub const N_FEATURES: usize = 20;

/// Fixed-point scale of leaf values and margins, as `2^LEAF_FRAC_BITS`.
pub const LEAF_FRAC_BITS: u32 = 20;

/// sha256 of `name:scale:monotone` over the feature contract, in order.
pub const FEATURE_CONTRACT: [u8; 32] = [
    0xa9, 0xe2, 0x67, 0x4a, 0x72, 0x1d, 0xed, 0x3d, 0xb8, 0x7b, 0x8a, 0xa2, 0xda, 0x0c, 0x09, 0xf0,
    0x2d, 0xce, 0xbd, 0x56, 0xea, 0x1c, 0x6f, 0x4d, 0xf5, 0x0b, 0x62, 0xe3, 0x5a, 0x45, 0x74, 0x03,
];

/// Feature order. Index `i` of the array passed to `advise` MUST be this feature.
pub const FEATURE_NAMES: [&str; N_FEATURES] = [
    "sched_class",
    "priority",
    "cpu_request",
    "memory_request",
    "disk_request",
    "diff_machine",
    "missing_info",
    "time_of_day",
    "task_index",
    "job_submits",
    "job_fails",
    "user_submits",
    "user_fails",
    "user_fail_rate",
    "user_terminals",
    "cell_submits_prev",
    "cell_fails_prev",
    "cell_sched_prev",
    "cell_evicts_prev",
    "cpu_x_mem",
];

/// Fixed-point scale applied to each feature before it is compared against a threshold.
pub const FEATURE_SCALES: [i64; N_FEATURES] = [
    1, 1, 65536, 65536, 65536, 1, 1, 1, 1, 1, 1, 1, 1, 10000, 1, 1, 1, 1, 1, 65536,
];
